# Do not print newline after prompt
add_newline = false


# [custom.talos]
# command = "talosctl config info | head -1 | cut -d: -f2 | xargs"
# when = "command -q talosctl"
# symbol = "üî∫"
# style = "red"
# format ='\[[$symbol$output]($style)\]'
# disabled = true

[shell]
fish_indicator = "Ôúπ"
powershell_indicator = "Óúè"
bash_indicator = "Óûï"
style = "blue bold"
disabled = false

[hostname]
disabled = false
ssh_only= true
format = "@ [$hostname]($style) "
style = "blue"

[directory]
truncation_length = 8
truncation_symbol = "‚Ä¶/"
read_only = " Ô†Ω"
[character]
success_symbol = "[·ëÄ](bold green) "
error_symbol = "[‚§¨](bold red) "

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "Ôî≠ "

[aws.region_aliases]
us-east-1 = "N. Virginia"
us-east-2 = "Ohio"
us-west-1 = "N. California"
us-west-2 = "Oregon"

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[‚è± $duration ]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = "ÔÑå "

[crystal]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = "Ôåà "

[dotnet]
format = '\[[$symbol($version)(üéØ $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = "Óâµ "

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "Ôêò "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = "Óòß "

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "Ôêò "

[java]
format = '\[[$symbol($version)]($style)\]'

symbol = "Óâñ "

[julia]
format = '\[[$symbol($version)]($style)\]'

symbol = "Óò§ "

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'
disabled = false

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "Ô°ö "

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = "Ôö§ "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

symbol = "Ôãú "

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "Ô£ñ "

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = "Óù© "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = "Óòà "

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "ÓòÜ "

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

symbol = "Óàæ "
[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "Óû® "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = "Óú∑ "

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = "ÔØ£ "

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

[shlvl]
symbol = "ÔÑ† "
